local:
  privatekey: "62bccd098743ab851901ac51e826722c5f414b1fdb40c6368ffdd048861fa6a6"
  network: "http://localhost:8545"
  chainid: 1337

testnet:
  privatekey: ""
  network: ""

mainnet:
  privatekey: ""
  network: ""
